In [1]:
import io
import numpy as np
import tensorflow as tf
from PIL import Image
from keras_preprocessing.image import array_to_img, img_to_array

# Load jpg

In [2]:
# img_path = "/data/aoi-wzs-p3-dip-prewave-saiap/unlabeled_cap-img/AluCap-ocv-class-2/Classified_01060113/270/A-20200107181349_PT4601_270_270_NA_0.png"
img_path = "/data/aoi-wzs-p1-dip-fa-nvidia/{0AEC1931-AE3A-4010-870B-13C3864AA377}.jpg"
img_string = open(img_path, 'rb').read()

In [4]:
b = tf.keras.preprocessing.image.load_img(img_path)
b = tf.keras.preprocessing.image.img_to_array(b)
print(b.dtype, b.shape, b[45, 43, :])

float32 (835, 777, 3) [11. 25. 26.]


In [3]:
# Load image directly
img_np = np.array(Image.open(io.BytesIO(img_string))) 
# img_np = np.asarray(img_np, dtype='float32')
print(img_np.dtype, img_np.shape, img_np[45, 43, :])

uint8 (835, 777, 3) [11 25 26]


In [12]:
b64tensor = tf.constant(img_string)
input_shape = tf.io.decode_image(b64tensor, expand_animations=False)
input_shape = input_shape.numpy().shape
b64tensor = tf.io.decode_raw(b64tensor, tf.uint8,fixed_length=1946385)
b64tensor

<tf.Tensor: shape=(1946385,), dtype=uint8, numpy=array([255, 216, 255, ...,   0,   0,   0], dtype=uint8)>

In [13]:
image = tf.reshape(b64tensor, input_shape)
print(image.dtype, image.shape, image[45, 43, :])

<dtype: 'uint8'> (835, 777, 3) tf.Tensor([0 0 0], shape=(3,), dtype=uint8)


In [3]:
# img_tensor = tf.io.read_file(img_path)
img_tensor = tf.constant(img_string)
# img_tensor = tf.io.decode_image(img_tensor, expand_animations=False)
img_tensor = tf.io.decode_jpeg(img_tensor,channels=3,dct_method="INTEGER_ACCURATE")
img_tensor = tf.cast(img_tensor, dtype=tf.float32)
it_np = img_tensor.numpy()
print(it_np.dtype, it_np.shape, it_np[45, 43, :])

float32 (835, 777, 3) [11. 25. 26.]


In [5]:
np.array_equal(it_np, b)

False

In [8]:
diff_np = np.equal(img_np, it_np)
diff_np
# for i in np.where(diff_np == False):
#     print(i, i.shape)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [False,  True,  True],
        [False,  True,  True],
        [False,  True,  True]],

       ...,

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        ...,
        [False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True, False, False],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [False, False,  True],
        [ True,  True,  True],
        [ True,

# Load png

In [9]:
img_path = "./1880606744_23e3dc4f6b_n.png"
img_string = open(img_path, 'rb').read()

In [10]:
# Load image directly
img_np = np.array(Image.open(io.BytesIO(img_string))) 
print(img_np.shape, img_np[0, 0, :])

(224, 224, 3) [232 232 232]


In [11]:
# Load string and decode
img_tensor = tf.io.decode_image(img_string, expand_animations=False)
img_tensor = tf.cast(img_tensor, dtype=tf.float32)
img_tensor = img_tensor.numpy()
print(img_tensor.shape, img_tensor[0, 0, :])

(224, 224, 3) [232. 232. 232.]


In [12]:
np.array_equal(img_np, img_tensor)

True